registry: registry.head-labs.com
imagePullPolicy: Always

serviceAccount:
  create: true
  annotations: {}
  name: "ton-service-account"

# Your docker registry keys
imagePullSecrets:
  - name: regcred

images:
  tonFullNode:
    name: ton/ton-node
    version: mainnet-v0 # `v0` - is version from pre-build.sh

  testnetFullNode:
    name: ton/ton-node
    version: testnet-v0

ports:
  # MAINNET
  tonFullNode:
    CONSOLE_PORT: 30001
    PUBLIC_PORT: 30002
    LITESERVER_PORT: 30003

  # TESTNET
  testnetFullNode:
    CONSOLE_PORT: 30004
    PUBLIC_PORT: 30005
    LITESERVER_PORT: 30006

env:
  # MAINNET
  - name: CONFIG
    value: https://test.ton.org/ton-global.config.json # mainnet config
  - name: LITESERVER # need to run liteserver on mainnet / not
    value: true

  # TESTNET
  - name: TESTNET_CONFIG
    value: https://newton-blockchain.github.io/testnet-global.config.json # testnet config
  - name: TESTNET_LITESERVER # need to run liteserver on testnet / not
    value: true

