registry: registry.head-labs.com
imagePullPolicy: Always
namespace: ton

# what services to run
run:
  mainnet: false
  testnet: true

# By default we create volume and mount it to /var/ton-work/db
persistent:
  tonFullNode:
    storageClassName: manual
    storageSize: 100Gi

  testnetFullNode:
    storageClassName: manual
    storageSize: 100Gi

serviceAccount:
  create: true
  name: "ton"

# Your docker registry keys
imagePullSecrets:
  - name: regcred

images:
  tonFullNode:
    name: ton/ton-node
    version: mainnet-v1

  testnetFullNode:
    name: ton/ton-node
    version: testnet-v1

  httpConfig:
    name: ton/ton-http-config
    version: v1

ports:
  # MAINNET
  tonFullNode:
    CONSOLE_PORT: 30001
    PUBLIC_PORT: 30002
    LITESERVER_PORT: 30003

  # TESTNET
  testnetFullNode:
    CONSOLE_PORT: 30004
    PUBLIC_PORT: 30005
    LITESERVER_PORT: 30006

  httpConfig:
    PUBLIC_PORT: 8081

env:
  # MAINNET
  - name: CONFIG
    value: https://test.ton.org/ton-global.config.json # mainnet config
  - name: LITESERVER # need to run liteserver on mainnet / not
    value: true

  # TESTNET
  - name: TESTNET_CONFIG
    value: https://newton-blockchain.github.io/testnet-global.config.json # testnet config
  - name: TESTNET_LITESERVER # need to run liteserver on testnet / not
    value: true

