---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: ton-testnet-database
spec:
  storageClassName: {{ .Values.persistent.testnetFullNode.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  {{ .Values.persistent.testnetFullNode.storageSize }}
---