apiVersion: v1
kind: Service
metadata:
  name: ton-mainnet
  labels:
    run: ton-mainnet
spec:
  ports:
  - targetPort: {{ .Values.ports.tonFullNode.PUBLIC_PORT }}
    name: ton-node
    protocol: UDP
    port: {{ .Values.ports.tonFullNode.PUBLIC_PORT }}
  - targetPort: {{ .Values.ports.tonFullNode.CONSOLE_PORT }}
    name: ton-client
    protocol: UDP
    port: {{ .Values.ports.tonFullNode.CONSOLE_PORT }}
  - targetPort: {{ .Values.ports.tonFullNode.LITESERVER_PORT }}
    name: ton-liteserver
    protocol: UDP
    port: {{ .Values.ports.tonFullNode.LITESERVER_PORT }}
  type: LoadBalancer
  selector:
    run: ton-mainnet
  externalIPs:
    - 94.130.163.226
---
apiVersion: v1
kind: Service
metadata:
  name: ton-testnet
  labels:
    run: ton-testnet
spec:
  ports:
  - targetPort: {{ .Values.ports.testnetFullNode.PUBLIC_PORT }}
    name: testnet-node
    protocol: UDP
    port: {{ .Values.ports.testnetFullNode.PUBLIC_PORT }}
  - targetPort: {{ .Values.ports.testnetFullNode.CONSOLE_PORT }}
    name: testnet-client
    protocol: UDP
    port: {{ .Values.ports.testnetFullNode.CONSOLE_PORT }}
  - targetPort: {{ .Values.ports.testnetFullNode.LITESERVER_PORT }}
    name: testnet-liteserver
    protocol: UDP
    port: {{ .Values.ports.testnetFullNode.LITESERVER_PORT }}
  type: LoadBalancer
  selector:
    run: ton-testnet
  externalIPs:
    - 94.130.163.226
---
