apiVersion: v1
kind: Service
metadata:
  name: ton-mainnet
  labels:
    run: ton-mainnet
spec:
  ports:
  - targetPort: ton-public-port
    protocol: UDP
    port: {{ .Values.ports.tonFullNode.PUBLIC_PORT }}
  - targetPort: ton-console-port
    protocol: UDP
    port: {{ .Values.ports.tonFullNode.CONSOLE_PORT }}
  - targetPort: liteserver-port
    protocol: UDP
    port: {{ .Values.ports.tonFullNode.LITESERVER_PORT }}
  selector:
    run: ton-mainnet
---
apiVersion: v1
kind: Service
metadata:
  name: ton-testnet
  labels:
    run: ton-testnet
spec:
  ports:
  - targetPort: testnet-ton-public-port
    protocol: UDP
    port: {{ .Values.ports.testnetFullNode.PUBLIC_PORT }}
  - targetPort: testnet-ton-console-port
    protocol: UDP
    port: {{ .Values.ports.testnetFullNode.CONSOLE_PORT }}
  - targetPort: testnet-liteserver-port
    protocol: UDP
    port: {{ .Values.ports.testnetFullNode.LITESERVER_PORT }}
  selector:
    run: ton-testnet