apiVersion: apps/v1
kind: Deployment
metadata:
  name: ton-mainnet-deployment
  labels:
    app: ton-mainnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ton-mainnet
  template:
    metadata:
      labels:
        app: ton-mainnet
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
      - name: ton-mainnet
        image: "{{ .Values.registry }}/{{ .Values.images.tonFullNode.name }}:{{ .Values.images.tonFullNode.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.ports.tonFullNode.PUBLIC_PORT }}
          protocol: UDP
        - containerPort: {{ .Values.ports.tonFullNode.CONSOLE_PORT }}
          protocol: UDP
        - containerPort: {{ .Values.ports.tonFullNode.LITESERVER_PORT }}
          protocol: UDP
        env:
          - name: PUBLIC_PORT
            value: "{{ .Values.ports.tonFullNode.PUBLIC_PORT }}"
          - name: CONSOLE_PORT
            value: "{{ .Values.ports.tonFullNode.CONSOLE_PORT }}"
          - name: LITESERVER_PORT
            value: "{{ .Values.ports.tonFullNode.LITESERVER_PORT }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ton-testnet-deployment
  labels:
    app: ton-testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ton-testnet
  template:
    metadata:
      labels:
        app: ton-testnet
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
      - name: ton-testnet
        image: "{{ .Values.registry }}/{{ .Values.images.testnetFullNode.name }}:{{ .Values.images.testnetFullNode.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.ports.testnetFullNode.PUBLIC_PORT }}
          protocol: UDP
        - containerPort: {{ .Values.ports.testnetFullNode.CONSOLE_PORT }}
          protocol: UDP
        - containerPort: {{ .Values.ports.testnetFullNode.LITESERVER_PORT }}
          protocol: UDP
        env:
          - name: PUBLIC_PORT
            value: "{{ .Values.ports.testnetFullNode.PUBLIC_PORT }}"
          - name: CONSOLE_PORT
            value: "{{ .Values.ports.testnetFullNode.CONSOLE_PORT }}"
          - name: LITESERVER_PORT
            value: "{{ .Values.ports.testnetFullNode.LITESERVER_PORT }}"