{{- if .Values.run.testnet -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: ton-testnet-load-balancer
  labels:
    run: ton-testnet-load-balancer
spec:
  ports:
  - targetPort: {{ .Values.ports.testnetFullNode.PUBLIC_PORT }}
    name: testnet-node
    protocol: UDP
    port: {{ .Values.ports.testnetFullNode.PUBLIC_PORT }}
    nodePort: {{ .Values.ports.testnetFullNode.PUBLIC_PORT }}
  - targetPort: {{ .Values.ports.testnetFullNode.CONSOLE_PORT }}
    name: testnet-client
    protocol: UDP
    port: {{ .Values.ports.testnetFullNode.CONSOLE_PORT }}
    nodePort: {{ .Values.ports.testnetFullNode.CONSOLE_PORT }}
  - targetPort: {{ .Values.ports.testnetFullNode.LITESERVER_PORT }}
    name: testnet-liteserver
    protocol: UDP
    port: {{ .Values.ports.testnetFullNode.LITESERVER_PORT }}
    nodePort: {{ .Values.ports.testnetFullNode.LITESERVER_PORT }}
  type: LoadBalancer
  selector:
    app: ton-testnet
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: ton-http-config-load-balancer
  labels:
    run:ton-http-config-load-balancer
spec:
  ports:
  - targetPort: {{ .Values.ports.httpConfig.PUBLIC_PORT }}
    name: http-config-testnet
    protocol: TCP
    port: {{ .Values.ports.httpConfig.PUBLIC_PORT }}
    nodePort: {{ .Values.ports.httpConfig.PUBLIC_PORT }}
  type: LoadBalancer
  selector:
    app: ton-testnet
{{- end }}
