{{- if .Values.run.mainnet -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: ton-mainnet-deployment
  labels:
    app: ton-mainnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ton-mainnet
  template:
    metadata:
      labels:
        app: ton-mainnet
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
      - name: ton-mainnet
        image: "{{ .Values.registry }}/{{ .Values.images.tonFullNode.name }}:{{ .Values.images.tonFullNode.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.customEnv.tonFullNode.PUBLIC_PORT }}
          protocol: UDP
        - containerPort: {{ .Values.customEnv.tonFullNode.CONSOLE_PORT }}
          protocol: UDP
        - containerPort: {{ .Values.customEnv.tonFullNode.LITESERVER_PORT }}
          protocol: UDP
        env:
          - name: PUBLIC_PORT
            value: "{{ .Values.customEnv.tonFullNode.PUBLIC_PORT }}"
          - name: CONSOLE_PORT
            value: "{{ .Values.customEnv.tonFullNode.CONSOLE_PORT }}"
          - name: LITESERVER_PORT
            value: "{{ .Values.customEnv.tonFullNode.LITESERVER_PORT }}"
          - name: NAMESPACE
            value: "{{ .Values.namespace }}"
          - name: SERVICE_ACCOUNT
            value: "{{ .Values.serviceAccount.name }}"
          {{- toYaml .Values.customEnv.tonFullNode.env | nindent 10 }}
        volumeMounts:
          - mountPath: "/var/ton-work/db/"
            name: ton-database
            subPath: db
          - mountPath: "/var/ton-work/network/"
            name: ton-database
            subPath: network
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/secret-volume"
      - name: ton-http-config
        image: "{{ .Values.registry }}/{{ .Values.images.httpConfig.name }}:{{ .Values.images.httpConfig.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.customEnv.httpConfig.PUBLIC_PORT }}
          protocol: TCP
        env:
          - name: PUBLIC_PORT
            value: "{{ .Values.customEnv.httpConfig.PUBLIC_PORT }}"
        volumeMounts:
          - mountPath: "/var/ton-work/network/"
            name: ton-database
            subPath: network
      volumes:
        - name: ton-database
          persistentVolumeClaim:
            claimName: ton-database
        - name: secret-volume
          secret:
            secretName: {{ .Values.serviceAccount.name }}-token-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: ton-toncenter
  labels:
    app: ton-mainnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ton-mainnet
  template:
    metadata:
      labels:
        app: ton-mainnet
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
      - name: ton-toncenter
        image: "{{ .Values.registry }}/{{ .Values.images.toncenter.name }}:{{ .Values.images.toncenter.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.customEnv.toncenter.PUBLIC_PORT }}
          protocol: TCP
        env:
          - name: PUBLIC_PORT
            value: "{{ .Values.customEnv.toncenter.PUBLIC_PORT }}"
          - name: CONFIG
            value: "{{ .Values.customEnv.toncenter.CONFIG }}"
          {{- toYaml .Values.customEnv.toncenter.env | nindent 10 }}
      {{- toYaml .Values.nodeSelector.mainnet | nindent 6 }}
---
{{- end }}
