{{- if .Values.run.ownnet -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: ton-ownnet-deployment
  labels:
    app: ton-ownnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ton-ownnet
  template:
    metadata:
      labels:
        app: ton-ownnet
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
      - name: ton-ownnet
        image: "{{ .Values.registry }}/{{ .Values.images.testnetFullNode.name }}:{{ .Values.images.testnetFullNode.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.customEnv.testnetFullNode.PUBLIC_PORT }}
          protocol: UDP
        - containerPort: {{ .Values.customEnv.testnetFullNode.CONSOLE_PORT }}
          protocol: UDP
        - containerPort: {{ .Values.customEnv.testnetFullNode.LITESERVER_PORT }}
          protocol: UDP
        env:
          - name: PUBLIC_PORT
            value: "{{ .Values.customEnv.testnetFullNode.PUBLIC_PORT }}"
          - name: CONSOLE_PORT
            value: "{{ .Values.customEnv.testnetFullNode.CONSOLE_PORT }}"
          - name: LITESERVER_PORT
            value: "{{ .Values.customEnv.testnetFullNode.LITESERVER_PORT }}"
          - name: NAMESPACE
            value: "{{ .Values.namespace }}"
          - name: SERVICE_ACCOUNT
            value: "{{ .Values.serviceAccount.name }}"
          - name: CONFIG
            value: "{{ .Values.customEnv.testnetFullNode.CONFIG }}"
          - name: VERBOSE
            value: "{{ .Values.customEnv.testnetFullNode.VERBOSE }}"
        volumeMounts:
          - mountPath: "/var/ton-work/db/"
            name: ton-ownnet-database
            subPath: db
          - mountPath: "/var/ton-work/network/"
            name: ton-ownnet-database
            subPath: network
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/secret-volume"

      - name: ton-http-config
        image: "{{ .Values.registry }}/{{ .Values.images.httpConfig.name }}:{{ .Values.images.httpConfig.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.customEnv.httpConfig.PUBLIC_PORT }}
          protocol: TCP
        env:
          - name: PUBLIC_PORT
            value: "{{ .Values.customEnv.httpConfig.PUBLIC_PORT }}"
        volumeMounts:
          - mountPath: "/var/ton-work/network/"
            name: ton-ownnet-database
            subPath: network

      volumes:
        - name: ton-ownnet-database
          persistentVolumeClaim:
            claimName: ton-ownnet-database
        - name: secret-volume
          secret:
            secretName: {{ .Values.serviceAccount.name }}-token-secret
---
{{- end }}
