{{- if .Values.ingress.enabled -}}
{{- if .Values.run.ownnet -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ton-ownnet-ingress
  labels:
    app: ton-ownnet
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hosts.ownnetToncenter }}
      secretName: ton-ownnet-tls
  rules:
    - host: {{ .Values.ingress.hosts.ownnetToncenter }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: owntoncenter
                port:
                  number: {{ .Values.customEnv.ownnetToncenter.PUBLIC_PORT }}
---
{{- end }}
{{- end }}
