version: '3'

services:
  mainnet:
    container_name: mainnet
    image: ton-node-mainnet
    environment:
      - CONFIG=https://test.ton.org/ton-global.config.json
      - LITESERVER=true
      - CONSOLE_PORT=30001
      - PUBLIC_PORT=30002
      - LITESERVER_PORT=30003

  toncenter:
    container_name: http-toncenter
    image: ton-toncenter-mainnet
    restart: always
    ports:
      - 8082:8082
    volumes:
      - config:/var/ton-work/network
    environment:
      - CONFIG=https://test.ton.org/ton-global.config.json
      - PORT=8082
    env_file:
      - 'toncenter.env'
    depends_on:
      - "mainnet"