version: '3.4'

services:
  genesis:
    container_name: genesis
    image: ton-node-testnet
    environment:
      - GENESIS=true
      - PRIVATE_CONFIG=false
      - PUBLIC_IP=172.28.1.1
      - DHT_PORT=6302
    volumes:
      - genesis:/var/ton-work/db
      - config:/var/ton-work/network
    env_file:
      - 'genesis-common.env'

  dht-server:
    container_name: dht-server
    image: ton-node-testnet
    environment:
      - DHT_PORT=6302
    volumes:
      - genesis:/var/ton-work/db
      - config:/var/ton-work/network
    env_file:
      - 'genesis-common.env'
    depends_on:
      - "genesis"
    networks:
      default:
        ipv4_address: 172.28.1.1


  validator:
    container_name: validator
    image: ton-node-testnet
    volumes:
      - genesis:/var/ton-work/db
      - config:/var/ton-work/network
    restart: always
    depends_on:
      - "genesis"
      - "dht-server"
    environment:
      - GENESIS_VALIDATOR=true
    env_file:
      - 'genesis-common.env'
#
#  onwnet-node:
#    image: ton-node-testnet
#    restart: always
#    volumes:
#      - config:/var/ton-work/network
#    depends_on:
#      - "genesis"
#      - "validator"
#    env_file:
#      - 'genesis-common.env'
#    deploy:
#      replicas: 3 # up to 50 validators (check gen-zerostate, wallets count)


volumes:
  config:
    external: false
  genesis:
    external: false

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
