version: '3'

services:
  genesis-dht-server:
    container_name: genesis-dht-server
    image: ton-node-testnet
    environment:
      - CONFIG=https://newton-blockchain.github.io/testnet-global.config.json
      - LITESERVER=true
      - CONSOLE_PORT=30004
      - PUBLIC_PORT=30005
      - LITESERVER_PORT=30006
      - GENESIS=true
      - DHT_PORT=6302
      - IP_GET_MODE=docker
    volumes:
      - genesis:/var/ton-work/db
      - config:/var/ton-work/network

  validator:
    container_name: validator
    image: ton-node-testnet
    environment:
      - PRIVATE_CONFIG=true
      - LITESERVER=true
      - CONSOLE_PORT=30004
      - PUBLIC_PORT=30005
      - LITESERVER_PORT=30006
      - DHT_PORT=6302
      - IP_GET_MODE=docker
    volumes:
      - genesis:/var/ton-work/db
      - config:/var/ton-work/network
    restart: always

  onwnet-node:
    image: ton-node-testnet
    restart: always
    environment:
      - LITESERVER=true
      - CONSOLE_PORT=30004
      - PUBLIC_PORT=30005
      - LITESERVER_PORT=30006
      - PRIVATE_CONFIG=true
      - IP_GET_MODE=docker
    volumes:
      - config:/var/ton-work/network
    deploy:
      replicas: 3

volumes:
  config:
    external: false
  genesis:
    external: false
